import * as fs from 'fs'
import * as path from 'path'
import { fileURLToPath } from 'url'

const __filename = fileURLToPath(import.meta.url)
const __dirname = path.dirname(__filename)

interface ScrapedProduct {
  name: string
  slug: string
  description: string
  price: number
  salePrice: number | null
  images: string[]
  category: string
  collection: string
  ingredients: string | null
  benefits: string | null
  howToUse: string | null
  inStock: boolean
  featured: boolean
}

const collections = [
  { name: 'BioHack: Anti-Aging Serums', slug: 'anti-aging-serums', category: 'Serums' },
  { name: 'Hydration Station: Moisturizers', slug: 'moisturizers', category: 'Moisturizers' },
  { name: 'Squeaky Clean: Soaps & Cleansers', slug: 'cleansers', category: 'Cleansers' },
  { name: 'Sunday Self-Care Rituals', slug: 'self-care', category: 'Rituals' },
  { name: 'Rise & Glow', slug: 'rise-and-glow', category: 'Bundles' },
  { name: 'Knowledge Is Beauty: eBooks', slug: 'ebooks', category: 'eBooks' },
  { name: 'Man up!', slug: 'mens', category: 'Mens' },
  { name: 'Save with Bundles', slug: 'bundles', category: 'Bundles' },
]

// Sample product data based on scraping results
const products: ScrapedProduct[] = [
  {
    name: '100 Beauty Tips: Free Download',
    slug: '100-beauty-tips-free-download',
    description: 'Unlock the secrets to radiant beauty with our comprehensive guide featuring 100 expert tips covering skincare, makeup, hair care, and wellness. From morning routines to nighttime rituals, discover professional techniques for every aspect of your beauty journey.',
    price: 0,
    salePrice: null,
    images: ['/images/products/100-beauty-tips.jpg'],
    category: 'eBooks',
    collection: 'ebooks',
    ingredients: null,
    benefits: 'Learn professional beauty techniques, develop personalized routines, understand ingredient science',
    howToUse: 'Download and read at your leisure. Implement tips gradually for best results.',
    inStock: true,
    featured: true,
  },
  {
    name: '100 Fashion Tips',
    slug: '100-fashion-tips',
    description: 'Elevate your style with 100 curated fashion tips from industry experts. Learn how to build a versatile wardrobe, master color coordination, and develop your personal style signature.',
    price: 5.95,
    salePrice: null,
    images: ['/images/products/100-fashion-tips.jpg'],
    category: 'eBooks',
    collection: 'ebooks',
    ingredients: null,
    benefits: 'Build a capsule wardrobe, learn styling techniques, develop personal style',
    howToUse: 'Digital download - read on any device',
    inStock: true,
    featured: false,
  },
  {
    name: '99 Make Up Tips',
    slug: '99-make-up-tips',
    description: 'Master the art of makeup with 99 professional tips and techniques. From everyday natural looks to glamorous evening styles, this guide covers everything you need to enhance your beauty.',
    price: 5.95,
    salePrice: null,
    images: ['/images/products/99-makeup-tips.jpg'],
    category: 'eBooks',
    collection: 'ebooks',
    ingredients: null,
    benefits: 'Learn professional makeup techniques, understand face shapes, master color theory',
    howToUse: 'Digital download - practice techniques with your own products',
    inStock: true,
    featured: false,
  },
  {
    name: 'Active Eye Cream',
    slug: 'active-eye-cream',
    description: 'Revitalize the delicate eye area with our potent Active Eye Cream. Formulated with peptides and caffeine to reduce puffiness, minimize dark circles, and smooth fine lines for a refreshed, youthful appearance.',
    price: 75.24,
    salePrice: 38.00,
    images: ['/images/products/active-eye-cream.jpg'],
    category: 'Serums',
    collection: 'anti-aging-serums',
    ingredients: 'Aqua, Caffeine, Peptide Complex, Hyaluronic Acid, Vitamin E, Aloe Vera, Green Tea Extract, Retinol, Niacinamide',
    benefits: 'Reduces puffiness, minimizes dark circles, smooths fine lines, hydrates delicate eye area',
    howToUse: 'Apply a small amount around the eye area morning and night. Gently pat until absorbed. Avoid direct contact with eyes.',
    inStock: true,
    featured: true,
  },
  {
    name: 'All-in-one Body Wash',
    slug: 'all-in-one-body-wash',
    description: 'Simplify your shower routine with our All-in-one Body Wash. This versatile formula cleanses, moisturizes, and refreshes your skin in one step, leaving you feeling clean and hydrated.',
    price: 49.95,
    salePrice: null,
    images: ['/images/products/all-in-one-body-wash.jpg'],
    category: 'Cleansers',
    collection: 'cleansers',
    ingredients: 'Aqua, Coconut-derived Surfactants, Aloe Vera, Vitamin E, Essential Oils, Glycerin',
    benefits: 'Cleanses without stripping, moisturizes skin, refreshing scent',
    howToUse: 'Apply to wet skin, lather, and rinse thoroughly.',
    inStock: true,
    featured: false,
  },
  {
    name: 'Anti-aging Rose Gold Oil',
    slug: 'anti-aging-rose-gold-oil',
    description: 'Luxurious face oil infused with rose gold particles and potent anti-aging botanicals. This lightweight yet nourishing formula absorbs quickly to deliver deep hydration and a radiant, youthful glow.',
    price: 29.95,
    salePrice: null,
    images: ['/images/products/rose-gold-oil.jpg'],
    category: 'Serums',
    collection: 'anti-aging-serums',
    ingredients: 'Rosehip Seed Oil, Jojoba Oil, Vitamin E, Rose Gold Particles, Rosemary Extract, Lavender Oil',
    benefits: 'Deep hydration, anti-aging properties, radiant glow, improves skin texture',
    howToUse: 'Apply 2-3 drops to cleansed face and neck. Gently massage in upward motions. Use morning and night.',
    inStock: true,
    featured: true,
  },
  {
    name: 'Antioxidant Toner',
    slug: 'antioxidant-toner',
    description: 'Protect and refresh your skin with our Antioxidant Toner. Packed with vitamin C and green tea extracts, this alcohol-free formula balances pH levels while defending against environmental stressors.',
    price: 22.95,
    salePrice: null,
    images: ['/images/products/antioxidant-toner.jpg'],
    category: 'Serums',
    collection: 'anti-aging-serums',
    ingredients: 'Aqua, Vitamin C, Green Tea Extract, Witch Hazel, Aloe Vera, Niacinamide, Hyaluronic Acid',
    benefits: 'Balances skin pH, protects against free radicals, hydrates, preps skin for serums',
    howToUse: 'After cleansing, apply to cotton pad and sweep across face and neck. Follow with serum and moisturizer.',
    inStock: true,
    featured: false,
  },
  {
    name: 'Ayonne Gift Cards',
    slug: 'ayonne-gift-cards',
    description: 'Give the gift of beauty with Ayonne Gift Cards. Perfect for any occasion, let your loved ones choose their favorite skincare products and beauty essentials.',
    price: 9.95,
    salePrice: null,
    images: ['/images/products/gift-card.jpg'],
    category: 'Gift Cards',
    collection: 'bundles',
    ingredients: null,
    benefits: 'Flexible gifting, never expires, can be used on any product',
    howToUse: 'Enter gift card code at checkout to redeem.',
    inStock: true,
    featured: false,
  },
  {
    name: 'Hemp Infused Beard Oil',
    slug: 'hemp-infused-beard-oil',
    description: 'Nourish and condition your beard with our Hemp Infused Beard Oil. This lightweight formula tames unruly hair, reduces itchiness, and promotes healthy beard growth while providing a subtle, masculine scent.',
    price: 23.00,
    salePrice: null,
    images: ['/images/products/hemp-beard-oil.jpg'],
    category: 'Mens',
    collection: 'mens',
    ingredients: 'Hemp Seed Oil, Jojoba Oil, Argan Oil, Vitamin E, Cedarwood Essential Oil, Eucalyptus Oil',
    benefits: 'Softens beard hair, reduces itchiness, promotes growth, adds shine',
    howToUse: 'Apply a few drops to palm, rub hands together, and massage into beard and skin beneath. Use daily.',
    inStock: true,
    featured: false,
  },
  {
    name: 'Rise & Glow Bundle',
    slug: 'rise-and-glow-bundle',
    description: 'Start your day with our complete Rise & Glow Bundle. This curated collection includes everything you need for a morning skincare routine that leaves your skin refreshed, hydrated, and glowing.',
    price: 267.95,
    salePrice: null,
    images: ['/images/products/rise-glow-bundle.jpg'],
    category: 'Bundles',
    collection: 'rise-and-glow',
    ingredients: null,
    benefits: 'Complete morning routine, savings vs. individual purchase, perfectly paired products',
    howToUse: 'Follow the included routine guide for optimal results.',
    inStock: true,
    featured: true,
  },
  {
    name: 'Vitamin C Brightening Toner',
    slug: 'vitamin-c-brightening-toner',
    description: 'Illuminate your complexion with our Vitamin C Brightening Toner. This potent formula helps fade dark spots, even skin tone, and boost radiance while preparing your skin for the rest of your routine.',
    price: 36.95,
    salePrice: null,
    images: ['/images/products/vitamin-c-toner.jpg'],
    category: 'Serums',
    collection: 'anti-aging-serums',
    ingredients: 'Aqua, Ascorbic Acid (Vitamin C), Ferulic Acid, Hyaluronic Acid, Aloe Vera, Niacinamide',
    benefits: 'Brightens skin, fades dark spots, evens skin tone, provides antioxidant protection',
    howToUse: 'After cleansing, apply to face and neck with cotton pad or fingertips. Follow with serum and moisturizer.',
    inStock: true,
    featured: true,
  },
  {
    name: 'Bamboo Beard Comb',
    slug: 'bamboo-beard-comb',
    description: 'Style your beard sustainably with our eco-friendly Bamboo Beard Comb. The smooth, anti-static teeth glide through facial hair without pulling, while the compact size makes it perfect for travel.',
    price: 18.00,
    salePrice: null,
    images: ['/images/products/bamboo-beard-comb.jpg'],
    category: 'Mens',
    collection: 'mens',
    ingredients: null,
    benefits: 'Anti-static, portable, eco-friendly, gentle on hair',
    howToUse: 'Gently comb through beard to detangle and style. Use after applying beard oil for best distribution.',
    inStock: true,
    featured: false,
  },
  {
    name: 'Beard Butter',
    slug: 'beard-butter',
    description: 'Deep conditioning beard butter that softens coarse facial hair and nourishes the skin beneath. This rich, creamy formula provides long-lasting moisture and a natural, healthy shine.',
    price: 41.58,
    salePrice: 21.00,
    images: ['/images/products/beard-butter.jpg'],
    category: 'Mens',
    collection: 'mens',
    ingredients: 'Shea Butter, Coconut Oil, Argan Oil, Beeswax, Vitamin E, Essential Oils',
    benefits: 'Softens beard, moisturizes skin, provides hold, reduces beardruff',
    howToUse: 'Scoop a small amount, warm between palms, and work through beard from roots to tips.',
    inStock: true,
    featured: false,
  },
  {
    name: 'Beard Nylon Brush',
    slug: 'beard-nylon-brush',
    description: 'Professional-grade nylon bristle brush designed specifically for beard grooming. Distributes oils evenly, removes debris, and helps train beard hair to grow in the desired direction.',
    price: 19.95,
    salePrice: null,
    images: ['/images/products/beard-brush.jpg'],
    category: 'Mens',
    collection: 'mens',
    ingredients: null,
    benefits: 'Distributes products evenly, exfoliates skin, trains hair growth, removes debris',
    howToUse: 'Brush through beard daily, starting from the neck and working upward, then downward to shape.',
    inStock: true,
    featured: false,
  },
  {
    name: 'Beard Oil - Classic',
    slug: 'beard-oil-classic',
    description: 'Our signature Beard Oil in a timeless Classic scent. This nourishing blend of premium oils hydrates, softens, and adds a healthy shine to your facial hair while soothing the skin beneath.',
    price: 20.95,
    salePrice: null,
    images: ['/images/products/beard-oil-classic.jpg'],
    category: 'Mens',
    collection: 'mens',
    ingredients: 'Jojoba Oil, Argan Oil, Sweet Almond Oil, Vitamin E, Cedarwood, Sandalwood, Bergamot',
    benefits: 'Hydrates beard and skin, reduces itchiness, classic masculine scent',
    howToUse: 'Apply 3-5 drops to palm, rub hands together, and massage into beard and skin. Use daily after showering.',
    inStock: true,
    featured: false,
  },
  {
    name: 'Beard Oil - Speakeasy',
    slug: 'beard-oil-speakeasy',
    description: 'A sophisticated Beard Oil with our exclusive Speakeasy scent. Notes of bourbon, tobacco, and oak create a distinguished aroma while premium oils condition and strengthen your beard.',
    price: 20.95,
    salePrice: null,
    images: ['/images/products/beard-oil-speakeasy.jpg'],
    category: 'Mens',
    collection: 'mens',
    ingredients: 'Jojoba Oil, Argan Oil, Grapeseed Oil, Vitamin E, Oak Moss, Tobacco Leaf, Vanilla, Bourbon Extract',
    benefits: 'Sophisticated scent, deep conditioning, promotes healthy growth',
    howToUse: 'Apply 3-5 drops to palm, rub hands together, and massage into beard and skin. Use daily.',
    inStock: true,
    featured: false,
  },
  {
    name: 'Hyaluronic Moisturizer',
    slug: 'hyaluronic-moisturizer',
    description: 'A rich cream that combines hyaluronic acid with a boost of a plant-based alternative tamarindus indica seed gum delivering plumping and hydrating benefits. Contains 4% shea butter and vitamin E for deep nourishment.',
    price: 54.95,
    salePrice: null,
    images: ['/images/products/hyaluronic-moisturizer.jpg'],
    category: 'Moisturizers',
    collection: 'moisturizers',
    ingredients: 'Aqua, Sunflower Seed Oil, Shea Butter, Glycerin, Sodium Hyaluronate, Green Tea Oil, Vitamin E, Squalane, Tamarindus Indica Seed Gum',
    benefits: 'Plumps skin, locks in moisture, nourishes deeply, improves skin texture',
    howToUse: 'Apply to cleansed skin morning and night. Recommended to use with the Firm Serum for very dry skin types.',
    inStock: false,
    featured: true,
  },
  {
    name: 'Embrace Collagen Moisturizer',
    slug: 'embrace-collagen-moisturizer',
    description: 'Luxurious collagen-infused moisturizer that helps restore skin elasticity and firmness. This advanced formula penetrates deeply to hydrate and support your skin\'s natural collagen production.',
    price: 55.00,
    salePrice: null,
    images: ['/images/products/embrace-collagen.jpg'],
    category: 'Moisturizers',
    collection: 'moisturizers',
    ingredients: 'Aqua, Marine Collagen, Peptide Complex, Hyaluronic Acid, Vitamin C, Retinol, Jojoba Oil, Aloe Vera',
    benefits: 'Boosts collagen production, improves elasticity, deeply hydrates, reduces wrinkles',
    howToUse: 'Apply generously to face and neck after serum. Use morning and night for best results.',
    inStock: true,
    featured: true,
  },
  {
    name: 'Collagen & Retinol Serum',
    slug: 'collagen-retinol-serum',
    description: 'Powerful anti-aging serum combining collagen-boosting peptides with retinol for maximum skin renewal. This potent formula targets fine lines, wrinkles, and uneven texture for visibly younger-looking skin.',
    price: 45.95,
    salePrice: null,
    images: ['/images/products/collagen-retinol-serum.jpg'],
    category: 'Serums',
    collection: 'anti-aging-serums',
    ingredients: 'Aqua, Retinol, Collagen Peptides, Hyaluronic Acid, Vitamin E, Niacinamide, Squalane',
    benefits: 'Reduces fine lines, boosts collagen, improves texture, promotes cell renewal',
    howToUse: 'Apply a few drops to cleansed skin at night. Start with 2-3 times per week and increase as tolerated. Always use SPF during the day.',
    inStock: true,
    featured: true,
  },
  {
    name: 'Glycolic Acid Serum',
    slug: 'glycolic-acid-serum',
    description: 'Exfoliating glycolic acid serum that gently removes dead skin cells to reveal brighter, smoother skin. This alpha-hydroxy acid treatment helps minimize pores and improve overall skin texture.',
    price: 32.95,
    salePrice: null,
    images: ['/images/products/glycolic-serum.jpg'],
    category: 'Serums',
    collection: 'anti-aging-serums',
    ingredients: 'Aqua, Glycolic Acid (10%), Aloe Vera, Hyaluronic Acid, Green Tea Extract, Vitamin E',
    benefits: 'Exfoliates dead skin, minimizes pores, brightens complexion, improves texture',
    howToUse: 'Apply to cleansed skin 2-3 times per week at night. Avoid eye area. Always use SPF during the day.',
    inStock: true,
    featured: false,
  },
  {
    name: 'Firming Serum',
    slug: 'firming-serum',
    description: 'Advanced firming serum designed to lift and tighten skin. This concentrated formula targets sagging and loss of firmness with a powerful blend of peptides and botanical extracts.',
    price: 48.95,
    salePrice: null,
    images: ['/images/products/firming-serum.jpg'],
    category: 'Serums',
    collection: 'anti-aging-serums',
    ingredients: 'Aqua, Peptide Complex, DMAE, Vitamin C, Hyaluronic Acid, Aloe Vera, Green Tea Extract',
    benefits: 'Lifts and firms, improves elasticity, tightens pores, enhances contours',
    howToUse: 'Apply to cleansed skin morning and night. Focus on areas prone to sagging. Follow with moisturizer.',
    inStock: true,
    featured: false,
  },
  {
    name: 'Charcoal Soap Bar',
    slug: 'charcoal-soap-bar',
    description: 'Detoxifying charcoal soap that draws out impurities and excess oil. This natural bar cleanses deeply while maintaining skin\'s moisture balance, perfect for oily and acne-prone skin.',
    price: 12.95,
    salePrice: null,
    images: ['/images/products/charcoal-soap.jpg'],
    category: 'Cleansers',
    collection: 'cleansers',
    ingredients: 'Activated Charcoal, Coconut Oil, Olive Oil, Shea Butter, Tea Tree Oil, Eucalyptus',
    benefits: 'Detoxifies skin, draws out impurities, controls oil, prevents breakouts',
    howToUse: 'Lather in hands and apply to wet skin. Massage gently and rinse thoroughly.',
    inStock: true,
    featured: false,
  },
  {
    name: 'Apricot Soap Bar',
    slug: 'apricot-soap-bar',
    description: 'Gentle exfoliating soap bar with natural apricot kernel powder. This fruity, nourishing cleanser buffs away dead skin cells while hydrating and softening your complexion.',
    price: 12.95,
    salePrice: null,
    images: ['/images/products/apricot-soap.jpg'],
    category: 'Cleansers',
    collection: 'cleansers',
    ingredients: 'Apricot Kernel Powder, Apricot Oil, Coconut Oil, Shea Butter, Vitamin E, Honey',
    benefits: 'Gentle exfoliation, hydrates skin, softens complexion, fruity scent',
    howToUse: 'Lather and massage onto damp skin in circular motions. Rinse thoroughly.',
    inStock: true,
    featured: false,
  },
  {
    name: 'Turmeric Soap Bar',
    slug: 'turmeric-soap-bar',
    description: 'Brightening turmeric soap bar that helps even skin tone and reduce hyperpigmentation. This anti-inflammatory cleanser soothes skin while delivering a natural, healthy glow.',
    price: 12.95,
    salePrice: null,
    images: ['/images/products/turmeric-soap.jpg'],
    category: 'Cleansers',
    collection: 'cleansers',
    ingredients: 'Turmeric Powder, Coconut Oil, Olive Oil, Honey, Vitamin E, Lemon Essential Oil',
    benefits: 'Brightens skin, evens tone, anti-inflammatory, natural glow',
    howToUse: 'Lather in hands and apply to wet skin. Leave on for 1-2 minutes for extra benefits before rinsing.',
    inStock: true,
    featured: false,
  },
  {
    name: 'Biohacker\'s Bundle',
    slug: 'biohackers-bundle',
    description: 'The ultimate anti-aging collection inspired by biohacking principles. This comprehensive bundle includes our most potent serums and treatments for those serious about reversing the signs of aging.',
    price: 235.95,
    salePrice: null,
    images: ['/images/products/biohackers-bundle.jpg'],
    category: 'Bundles',
    collection: 'bundles',
    ingredients: null,
    benefits: 'Complete anti-aging system, significant savings, scientifically formulated',
    howToUse: 'Follow the included step-by-step routine guide for optimal results.',
    inStock: true,
    featured: true,
  },
  {
    name: 'Niacinamide Serum',
    slug: 'niacinamide-serum',
    description: 'Multi-tasking niacinamide serum that minimizes pores, balances oil production, and improves skin texture. This vitamin B3 powerhouse also helps reduce the appearance of dark spots and blemishes.',
    price: 28.95,
    salePrice: null,
    images: ['/images/products/niacinamide-serum.jpg'],
    category: 'Serums',
    collection: 'anti-aging-serums',
    ingredients: 'Aqua, Niacinamide (10%), Zinc PCA, Hyaluronic Acid, Aloe Vera',
    benefits: 'Minimizes pores, controls oil, improves texture, fades dark spots',
    howToUse: 'Apply a few drops to cleansed skin morning and night before moisturizer.',
    inStock: true,
    featured: false,
  },
  {
    name: 'Vitamin E Oil',
    slug: 'vitamin-e-oil',
    description: 'Pure vitamin E oil for deep nourishment and skin repair. This versatile oil helps fade scars, moisturize dry patches, and protect skin from environmental damage.',
    price: 18.95,
    salePrice: null,
    images: ['/images/products/vitamin-e-oil.jpg'],
    category: 'Serums',
    collection: 'anti-aging-serums',
    ingredients: 'Tocopherol (Vitamin E), Sunflower Seed Oil, Jojoba Oil',
    benefits: 'Repairs skin, fades scars, deep moisture, antioxidant protection',
    howToUse: 'Apply a few drops to target areas or mix with moisturizer for all-over treatment.',
    inStock: true,
    featured: false,
  },
  {
    name: 'Sunday Self-Care Set',
    slug: 'sunday-self-care-set',
    description: 'Transform your Sundays into spa days with this indulgent self-care set. Includes everything you need for a relaxing at-home facial and body treatment.',
    price: 89.95,
    salePrice: null,
    images: ['/images/products/sunday-selfcare-set.jpg'],
    category: 'Rituals',
    collection: 'self-care',
    ingredients: null,
    benefits: 'Complete spa experience, relaxation, skin rejuvenation',
    howToUse: 'Follow the included ritual guide for a complete self-care experience.',
    inStock: true,
    featured: false,
  },
  {
    name: 'Hydrating Face Mist',
    slug: 'hydrating-face-mist',
    description: 'Refreshing hydrating mist that provides instant moisture and a dewy glow. Perfect for setting makeup, refreshing skin throughout the day, or adding extra hydration to your routine.',
    price: 24.95,
    salePrice: null,
    images: ['/images/products/face-mist.jpg'],
    category: 'Moisturizers',
    collection: 'moisturizers',
    ingredients: 'Aqua, Rose Water, Hyaluronic Acid, Aloe Vera, Glycerin, Cucumber Extract',
    benefits: 'Instant hydration, refreshes skin, sets makeup, dewy finish',
    howToUse: 'Spritz onto face from 8-10 inches away. Use anytime skin needs a refresh.',
    inStock: true,
    featured: false,
  },
  {
    name: 'Retinol Night Cream',
    slug: 'retinol-night-cream',
    description: 'Intensive overnight treatment featuring encapsulated retinol for gentle yet effective results. Wake up to smoother, more radiant skin as this powerful cream works while you sleep.',
    price: 58.95,
    salePrice: null,
    images: ['/images/products/retinol-night-cream.jpg'],
    category: 'Moisturizers',
    collection: 'moisturizers',
    ingredients: 'Aqua, Encapsulated Retinol, Peptides, Shea Butter, Vitamin E, Squalane, Hyaluronic Acid',
    benefits: 'Reduces wrinkles, smooths texture, promotes cell renewal, deep hydration',
    howToUse: 'Apply to cleansed skin at night as the last step in your routine. Use SPF during the day.',
    inStock: true,
    featured: false,
  },
]

async function main() {
  const outputDir = path.join(__dirname, '../prisma')

  // Generate seed data
  const seedData = {
    collections,
    products: products.map((p, index) => ({
      ...p,
      id: `prod_${String(index + 1).padStart(3, '0')}`,
    })),
  }

  // Write to JSON file for seeding
  fs.writeFileSync(
    path.join(outputDir, 'seed-data.json'),
    JSON.stringify(seedData, null, 2)
  )

  console.log(`Generated ${products.length} products and ${collections.length} collections`)
  console.log('Seed data written to prisma/seed-data.json')
}

main().catch(console.error)
